name: effectve_logger
description: Simple logger for Dart/Flutter
version: 1.0.3
repository: https://github.com/rvachev/logger

environment:
  sdk: ">=2.19.4 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
